spring.application.name=speech-to-text

# Database Connection

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Spring Data JPA

spring.jpa.show-sql=false

# Logging

logging.level.root=ERROR