spring.application.name=speech-to-text

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true

deepgram.api-key=${DEEPGRAM_API_KEY}
