spring.application.name=speech-to-text

spring.datasource.url=jdbc:postgresql://localhost:5432/stt_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true

jwt.private-key=certs/private.pem
jwt.public-key=certs/public.pem
